browser=chrome
browser1=Edge

browser_headless_chrome=chrome_headless

user=
password=
#################################### Pension Admin MBCTRA ###########################################################

################################ MBCKG1 client PPT(participants) ########################################################################
MBCKG1ACTIVEPPTURL=https://orangeorm.com



